//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UzduotisPraktikos.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Darbuotojai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Darbuotojai()
        {
            this.DarbuotojoPareigas = new HashSet<DarbuotojoPareiga>();
        }
    
        public int ID { get; set; }
        public string Vardas { get; set; }
        public string Pavarde { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Gimimo Data")]
        public Nullable<System.DateTime> GimimoData { get; set; }
        public string Adresas { get; set; }

        [UIHint("Aktyvumas")]
        public Nullable<bool> Aktyvus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DarbuotojoPareiga> DarbuotojoPareigas { get; set; }
    }
}
