//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UzduotisPraktikos.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PraktikosDarbuotojaiEntities : DbContext
    {
        public PraktikosDarbuotojaiEntities()
            : base("name=PraktikosDarbuotojaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Darbuotojai> Darbuotojais { get; set; }
        public virtual DbSet<DarbuotojoPareiga> DarbuotojoPareigas { get; set; }
        public virtual DbSet<Pareigo> Pareigos { get; set; }
    }
}
